### ISSUE TITLE
Bouton "Supprimer catégorie" : pas très UX

### ISSUE THREAD

**Issue by DrissB45** [WildCodeSchool/202209-orleans-php-project-originsdigital#386]
Petit bouton "supprimer" pas très bien placé, puis cliquer sur "Modifier" pour supprimer : pas très UX

![Capture d’écran du 2023-01-30 15-47-30](https://user-images.githubusercontent.com/109434733/215513334-8b1e8555-2645-4def-8df4-55d34d56ec82.png)

**Comment by shvilaine** [comment]
C'est supprimer l'image d'une catégorie, une feature de Symfony Forms.
Très difficile de changer.
