### ISSUE TITLE
Format différent du reste (boutons à la verticale)

### ISSUE THREAD

**Issue by DrissB45** [WildCodeSchool/202209-orleans-php-project-originsdigital#400]
![Capture d’écran du 2023-01-30 16-20-31](https://user-images.githubusercontent.com/109434733/215518200-d7b2dc19-a2bd-4b60-a21b-8f6c0d63023e.png)

**Comment by shvilaine** [comment]
Prévu dans le fix des boutons sur chaque sous-partie dans Admin
